"use client"

import { useState } from 'react';
import Link from 'next/link';
import { Inter } from "next/font/google";
import "./globals.css";

import { FaBars, FaTimes } from "react-icons/fa";



const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isProductDropdownOpen, setIsProductDropdownOpen] = useState(false);
  const [isResourcesDropdownOpen, setIsResourcesDropdownOpen] = useState(false);
  const [isSolutionsDropdownOpen, setIsSolutionsDropdownOpen] = useState(false);
  const [isEnDropdownOpen, setIsEnDropdownOpen] = useState(false);
  const [query, setQuery] = useState('');

  const handleSearch = (e) => {
    e.preventDefault();
    console.log('Searching for:', query);
  };

  const [isOpen, setIsOpen] = useState(false);
  const toggleMenu = () => {
    setIsOpen(!isOpen);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" fixed top-0 left-0 w-full bg-blue-600 text-black shadow-lg z-50">
          <nav className="shadow-lg bg-white ">
            <div className="block lg:hidden">
              {/* Mobile menu button*/}
              <button
                onClick={toggleMenu}
                className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
              >
                <span className="sr-only">Open main menu</span>
                {isOpen ? <FaTimes className="h-6 w-6" /> : <FaBars className="h-6 w-6" />}
              </button>
            </div>
            <div className="container mx-auto flex justify-around items-center px-6 py-4">

              <h1 className="text-4xl font-bold text-gray-900">OpenProject</h1>
              <ul className="lg:flex gap-2 text-sm font-medium  hidden ">
                <li
                  className="relative group"
                  onMouseEnter={() => setIsProductDropdownOpen(true)}
                  onMouseLeave={() => setIsProductDropdownOpen(false)}
                >
                  <Link href="/home/monthly" className="hover:text-gray-900 transition">PRODUCT</Link>
                  <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                  </svg>
                  {isProductDropdownOpen && (
                    <div
                      className="absolute left-0 mt-2 w-[800px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                      onMouseEnter={() => setIsProductDropdownOpen(true)}
                      onMouseLeave={() => setIsProductDropdownOpen(false)}
                    >
                      <div className="p-6 grid grid-cols-2 gap-6">
                        <div>
                          <div className="font-semibold text-gray-700 mb-3 text-lg">Features</div>
                          <ul className="space-y-2">
                            <li><a href="/collaboration-software-features/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Product tour</a></li>
                            <li><a href="/intro/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors"><i className="icon-video-play"></i> Watch introduction</a></li>
                            <li className="font-bold text-gray-700 mt-4 mb-2">Editions</li>
                            <li><a href="/community-edition/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Community edition</a></li>
                            <li><a href="/enterprise-edition/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Enterprise edition</a></li>
                            <li className="border-t border-gray-200 my-2"></li>
                            <li><a href="/security-and-privacy/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Security & data privacy</a></li>
                            <li><a href="/download-and-installation/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Download & installation</a></li>
                          </ul>
                        </div>
                        <div>
                          <div className="font-semibold text-gray-700 mb-3 text-lg">Integrations</div>
                          <ul className="space-y-2">
                            <li><a href="/docs/user-guide/file-management/nextcloud-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Nextcloud</a></li>
                            <li><a href="/docs/user-guide/file-management/one-drive-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">OneDrive/SharePoint</a></li>
                            <li><a href="/docs/system-admin-guide/integrations/github-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">GitHub</a></li>
                            <li><a href="/docs/system-admin-guide/integrations/gitlab-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">GitLab</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  )}
                </li>

                <li className="hover:text-gray-900 transition">
                  <Link href="/home/annual">PRICING</Link>
                </li>
                <li
                  className="relative group"
                  onMouseEnter={() => setIsResourcesDropdownOpen(true)}
                  onMouseLeave={() => setIsResourcesDropdownOpen(false)}
                >
                  <Link href="/home/monthly" className="hover:text-gray-900 transition">RESOURCES</Link>
                  <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                  </svg>
                  {isResourcesDropdownOpen && (
                    <div
                      className="absolute left-0 mt-2 w-[800px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                      onMouseEnter={() => setIsResourcesDropdownOpen(true)}
                      onMouseLeave={() => setIsResourcesDropdownOpen(false)}
                    >
                      <div className="p-6 grid grid-cols-3 gap-8">
                        <div className="w-full">
                          <div className="font-semibold text-gray-800 mb-3 text-lg">Product Resources</div>
                          <ul className="list-unstyled space-y-3">
                            <li><a href="/docs/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Documentation & Help</a></li>
                            <li><a href="https://www.youtube.com/c/OpenProjectCommunity" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors" target="_blank" rel="noopener noreferrer nofollow">Videos</a></li>
                            <li><a href="/project-management-software-alternatives/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Alternatives</a></li>
                            <li><a href="/blog/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Blog</a></li>
                          </ul>
                        </div>
                        <div className="w-full">
                          <div className="font-semibold text-gray-800 mb-3 text-lg">Support</div>
                          <ul className="list-unstyled space-y-3">
                            <li><a href="/contact/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Contact Us</a></li>
                            <li><a href="/docs/faq/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">FAQs</a></li>
                            <li><a href="/docs/glossary/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Glossary</a></li>
                            <li><a href="/training-and-consulting/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Training & Consulting</a></li>
                          </ul>
                        </div>
                        <div className="w-full">
                          <div className="font-semibold text-gray-800 mb-3 text-lg">Company</div>
                          <ul className="list-unstyled space-y-3">
                            <li><a href="/about-us/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">About Us</a></li>
                            <li><a href="/customers/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Customers</a></li>
                            <li><a href="/careers/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Careers</a></li>
                            <li><a href="/press/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Press</a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                  )}
                </li>


                <li
                  className="relative group"
                  onMouseEnter={() => setIsSolutionsDropdownOpen(true)}
                  onMouseLeave={() => setIsSolutionsDropdownOpen(false)}
                >
                  <Link href="/home/monthly" className="hover:text-gray-900 transition">SOLUTIONS</Link>
                  <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                  </svg>
                  {isSolutionsDropdownOpen && (
                    <ul
                      className="absolute left-0 mt-2 w-[900px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                      onMouseEnter={() => setIsSolutionsDropdownOpen(true)}
                      onMouseLeave={() => setIsSolutionsDropdownOpen(false)}
                    >
                      <div className="p-6 grid grid-cols-2 gap-8">
                        <div className="flex-1">
                          <div className="font-semibold text-gray-700 mb-3 text-lg">Industries</div>
                          <ul className="space-y-2">
                            <li><a href="/bim-project-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Construction | BIM</a></li>
                            <li><a href="/project-management-universities-research/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Universities, education & research</a></li>
                            <li><a href="/project-management-it-technology/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">IT & technology</a></li>
                            <li><a href="/project-management-public-sector/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Public & governmental organizations</a></li>
                            <li><a href="/project-management-healthcare/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Healthcare</a></li>
                            <li><a href="/project-management-automotive/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Automotive</a></li>
                            <li><a href="/project-management-engineering/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Engineering</a></li>
                            <li><a href="/project-management-ngos-foundations/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">NGO & foundations</a></li>
                            <li><a href="/project-management-banking-and-insurance/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Banking & insurance</a></li>
                          </ul>
                        </div>
                        <div className="flex-1">
                          <div className="font-semibold text-gray-700 mb-3 text-lg">Use cases</div>
                          <ul className="space-y-2">
                            <li><a href="/collaboration-software-features/project-portfolio-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project Portfolio Management</a></li>
                            <li><a href="/collaboration-software-features/project-planning-scheduling/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project Planning & Scheduling</a></li>
                            <li><a href="/collaboration-software-features/task-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Task management & issue tracking</a></li>
                            <li><a href="/collaboration-software-features/agile-project-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Agile, Kanban & Scrum</a></li>
                            <li><a href="/collaboration-software-features/time-tracking/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Time tracking, cost reporting & budgeting</a></li>
                            <li><a href="/collaboration-software-features/team-collaboration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Team collaboration</a></li>
                            <li><a href="/collaboration-software-features/product-development/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Product roadmap & release planning</a></li>
                            <li><a href="/collaboration-software-features/workflows-customization/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Workflows & customization</a></li>
                            <li><a href="/collaboration-software-features/project-management-process/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project management process</a></li>
                          </ul>
                        </div>
                      </div>
                    </ul>
                  )}
                </li>

                <li
                  className="relative group"
                  onMouseEnter={() => setIsEnDropdownOpen(true)}
                  onMouseLeave={() => setIsEnDropdownOpen(false)}
                >
                  <div className="flex items-center space-x-2">
                    <Link href="/home/monthly" className="hover:text-gray-900 transition">
                      EN
                    </Link>

                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6">
                      <path fillRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zM3.97 12.05c-.014.32-.02.641-.02.962 0 .32.006.641.02.96l2.086-1.062A7.965 7.965 0 013.97 12.05zm16.06-.001a8.015 8.015 0 00-2.086-1.062l2.085 1.063zM12 3.969a7.963 7.963 0 00-1.062 2.086l1.062-2.086zM8.837 6.222l-1.062 2.086 2.085-1.062a7.96 7.96 0 00-1.023-.55zm5.326 0a7.96 7.96 0 00-1.022.55l2.084 1.063-1.062-2.086zm-2.644.796l-1.063 2.084a7.95 7.95 0 00-2.086-1.062l1.063-2.085a7.963 7.963 0 002.086 1.062zM3.97 13.938a8.015 8.015 0 001.062 2.086l-2.086-1.062zM20.03 13.938a8.015 8.015 0 01-1.062 2.086l2.086-1.062zM15.133 17.777a7.96 7.96 0 001.022-.55l-2.084-1.063 1.062 2.086zm-6.267 0l1.062-2.086-2.084 1.063a7.96 7.96 0 001.022.55zm2.644-.797l1.063-2.084a7.95 7.95 0 002.086 1.062l-1.063 2.085a7.963 7.963 0 01-2.086-1.062zM12 20.03c-3.313 0-6-2.687-6-6 0-.32.006-.641.02-.961l1.062 2.086a7.95 7.95 0 01-2.086-1.062l2.085-1.063A7.963 7.963 0 0112 20.03zm6-6.97a7.963 7.963 0 01-2.086 1.062l1.062-2.086c.014.32.02.641.02.961zm-.796-3.135l-1.062-2.085a7.95 7.95 0 01-2.085 1.062l1.063 2.085a7.963 7.963 0 012.084-1.062zM12 19.969a7.963 7.963 0 001.062-2.086l-1.062 2.086zm-5.325-2.743l-2.086-1.062 1.062-2.085a7.963 7.963 0 002.086 1.062l-1.062 2.085zM9.613 9.365a7.95 7.95 0 002.086-1.062l-1.062 2.086a7.963 7.963 0 00-2.086 1.062l1.062-2.085z" clipRule="evenodd" />
                    </svg>

                    <svg className="w-5 h-5 text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                    </svg>
                  </div>

                  {isEnDropdownOpen && (
                    <ul className="absolute left-0 mt-2 w-48 bg-white text-gray-800 shadow-lg rounded-md group-hover:block transition-opacity duration-300 opacity-100">
                      <li>
                        <Link href="/home/en1" className="block px-4 py-2 hover:bg-gray-100">Deutsch</Link>
                      </li>
                      <li>
                        <Link href="/home/en2" className="block px-4 py-2 hover:bg-gray-100">Español</Link>
                      </li>
                      <li>
                        <Link href="/home/en3" className="block px-4 py-2 hover:bg-gray-100">Français</Link>
                      </li>
                    </ul>
                  )}
                </li>
              </ul>
              <form onSubmit={handleSearch} className="flex items-center">
                <input
                  type="text"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Search..."
                  className="py-2 px-4 rounded-l-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
                <button
                  type="submit"
                  className="py-2 px-4 bg-blue-500 text-white rounded-r-md border border-blue-500 hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500"
                >
                  Search
                </button>
              </form>

              <div className="flex items-center gap-4">
                <button className=" text-black font-thin py-2 px-4 rounded">
                  Sign in
                </button>
                <button className="bg-white border-2 border-blue-500 text-blue-500 font-semibold py-2 px-4 rounded-full hover:bg-blue-500 hover:text-white transition">
                  Install Open Project
                </button>

                <button className="bg-green-700 text-white font-semibold py-2 px-4  hover:bg-green-500 transition rounded-full">
                  Start For Free
                </button>

              </div>
            </div>
            {isOpen && (
              <div className='fixed top-0 left-0 h-[900px] z-10 w-64  bg-slate-600 block lg:hidden '>
                <button
                  onClick={toggleMenu}
                  className="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
                >
                  <span className="sr-only">Open main menu</span>
                  {isOpen ? <FaTimes className="h-6 w-6" /> : <FaBars className="h-6 w-6" />}
                </button>
                <ul className=" flex flex-col gap-6 ml-3">
                  <li
                    className="relative group"
                    onMouseEnter={() => setIsProductDropdownOpen(true)}
                    onMouseLeave={() => setIsProductDropdownOpen(false)}
                  >
                    <Link href="/home/monthly" className="hover:text-gray-900 transition">PRODUCT</Link>
                    <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                    </svg>
                    {isProductDropdownOpen && (
                      <div
                        className="absolute left-0 mt-2 w-[600px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                        onMouseEnter={() => setIsProductDropdownOpen(true)}
                        onMouseLeave={() => setIsProductDropdownOpen(false)}
                      >
                        <div className="p-6 grid grid-cols-2 gap-6">
                          <div>
                            <div className="font-semibold text-gray-700 mb-3 text-lg">Features</div>
                            <ul className="space-y-2">
                              <li><a href="/collaboration-software-features/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Product tour</a></li>
                              <li><a href="/intro/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors"><i className="icon-video-play"></i> Watch introduction</a></li>
                              <li className="font-bold text-gray-700 mt-4 mb-2">Editions</li>
                              <li><a href="/community-edition/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Community edition</a></li>
                              <li><a href="/enterprise-edition/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Enterprise edition</a></li>
                              <li className="border-t border-gray-200 my-2"></li>
                              <li><a href="/security-and-privacy/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Security & data privacy</a></li>
                              <li><a href="/download-and-installation/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Download & installation</a></li>
                            </ul>
                          </div>
                          <div>
                            <div className="font-semibold text-gray-700 mb-3 text-lg">Integrations</div>
                            <ul className="space-y-2">
                              <li><a href="/docs/user-guide/file-management/nextcloud-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Nextcloud</a></li>
                              <li><a href="/docs/user-guide/file-management/one-drive-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">OneDrive/SharePoint</a></li>
                              <li><a href="/docs/system-admin-guide/integrations/github-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">GitHub</a></li>
                              <li><a href="/docs/system-admin-guide/integrations/gitlab-integration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">GitLab</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    )}
                  </li>

                  <li className="hover:text-gray-900 transition">
                    <Link href="/home/annual">PRICING</Link>
                  </li>
                  <li
                    className="relative group"
                    onMouseEnter={() => setIsResourcesDropdownOpen(true)}
                    onMouseLeave={() => setIsResourcesDropdownOpen(false)}
                  >
                    <Link href="/home/monthly" className="hover:text-gray-900 transition">RESOURCES</Link>
                    <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                    </svg>
                    {isResourcesDropdownOpen && (
                      <div
                        className="absolute left-0 mt-2 w-[800px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                        onMouseEnter={() => setIsResourcesDropdownOpen(true)}
                        onMouseLeave={() => setIsResourcesDropdownOpen(false)}
                      >
                        <div className="p-6 grid grid-cols-3 gap-8">
                          <div className="w-full">
                            <div className="font-semibold text-gray-800 mb-3 text-lg">Product Resources</div>
                            <ul className="list-unstyled space-y-3">
                              <li><a href="/docs/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Documentation & Help</a></li>
                              <li><a href="https://www.youtube.com/c/OpenProjectCommunity" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors" target="_blank" rel="noopener noreferrer nofollow">Videos</a></li>
                              <li><a href="/project-management-software-alternatives/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Alternatives</a></li>
                              <li><a href="/blog/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Blog</a></li>
                            </ul>
                          </div>
                          <div className="w-full">
                            <div className="font-semibold text-gray-800 mb-3 text-lg">Support</div>
                            <ul className="list-unstyled space-y-3">
                              <li><a href="/contact/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Contact Us</a></li>
                              <li><a href="/docs/faq/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">FAQs</a></li>
                              <li><a href="/docs/glossary/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Glossary</a></li>
                              <li><a href="/training-and-consulting/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Training & Consulting</a></li>
                            </ul>
                          </div>
                          <div className="w-full">
                            <div className="font-semibold text-gray-800 mb-3 text-lg">Company</div>
                            <ul className="list-unstyled space-y-3">
                              <li><a href="/about-us/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">About Us</a></li>
                              <li><a href="/customers/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Customers</a></li>
                              <li><a href="/careers/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Careers</a></li>
                              <li><a href="/press/" className="block py-2 px-4 hover:bg-gray-100 rounded-lg transition-colors">Press</a></li>
                            </ul>
                          </div>
                        </div>
                      </div>
                    )}
                  </li>


                  <li
                    className="relative group"
                    onMouseEnter={() => setIsSolutionsDropdownOpen(true)}
                    onMouseLeave={() => setIsSolutionsDropdownOpen(false)}
                  >
                    <Link href="/home/monthly" className="hover:text-gray-900 transition">SOLUTIONS</Link>
                    <svg className="ml-2 w-5 h-5 inline-block text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                    </svg>
                    {isSolutionsDropdownOpen && (
                      <ul
                        className="absolute left-0 mt-2 w-[900px] bg-white text-gray-800 shadow-lg rounded-lg overflow-hidden transition-opacity duration-300 opacity-100 z-50"
                        onMouseEnter={() => setIsSolutionsDropdownOpen(true)}
                        onMouseLeave={() => setIsSolutionsDropdownOpen(false)}
                      >
                        <div className="p-6 grid grid-cols-2 gap-8">
                          <div className="flex-1">
                            <div className="font-semibold text-gray-700 mb-3 text-lg">Industries</div>
                            <ul className="space-y-2">
                              <li><a href="/bim-project-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Construction | BIM</a></li>
                              <li><a href="/project-management-universities-research/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Universities, education & research</a></li>
                              <li><a href="/project-management-it-technology/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">IT & technology</a></li>
                              <li><a href="/project-management-public-sector/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Public & governmental organizations</a></li>
                              <li><a href="/project-management-healthcare/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Healthcare</a></li>
                              <li><a href="/project-management-automotive/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Automotive</a></li>
                              <li><a href="/project-management-engineering/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Engineering</a></li>
                              <li><a href="/project-management-ngos-foundations/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">NGO & foundations</a></li>
                              <li><a href="/project-management-banking-and-insurance/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Banking & insurance</a></li>
                            </ul>
                          </div>
                          <div className="flex-1">
                            <div className="font-semibold text-gray-700 mb-3 text-lg">Use cases</div>
                            <ul className="space-y-2">
                              <li><a href="/collaboration-software-features/project-portfolio-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project Portfolio Management</a></li>
                              <li><a href="/collaboration-software-features/project-planning-scheduling/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project Planning & Scheduling</a></li>
                              <li><a href="/collaboration-software-features/task-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Task management & issue tracking</a></li>
                              <li><a href="/collaboration-software-features/agile-project-management/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Agile, Kanban & Scrum</a></li>
                              <li><a href="/collaboration-software-features/time-tracking/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Time tracking, cost reporting & budgeting</a></li>
                              <li><a href="/collaboration-software-features/team-collaboration/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Team collaboration</a></li>
                              <li><a href="/collaboration-software-features/product-development/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Product roadmap & release planning</a></li>
                              <li><a href="/collaboration-software-features/workflows-customization/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Workflows & customization</a></li>
                              <li><a href="/collaboration-software-features/project-management-process/" className="block py-2 px-4 hover:bg-gray-100 rounded transition-colors">Project management process</a></li>
                            </ul>
                          </div>
                        </div>
                      </ul>
                    )}
                  </li>

                  <li
                    className="relative group"
                    onMouseEnter={() => setIsEnDropdownOpen(true)}
                    onMouseLeave={() => setIsEnDropdownOpen(false)}
                  >
                    <div className="flex items-center space-x-2">
                      <Link href="/home/monthly" className="hover:text-gray-900 transition">
                        EN
                      </Link>

                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6">
                        <path fillRule="evenodd" d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zM3.97 12.05c-.014.32-.02.641-.02.962 0 .32.006.641.02.96l2.086-1.062A7.965 7.965 0 013.97 12.05zm16.06-.001a8.015 8.015 0 00-2.086-1.062l2.085 1.063zM12 3.969a7.963 7.963 0 00-1.062 2.086l1.062-2.086zM8.837 6.222l-1.062 2.086 2.085-1.062a7.96 7.96 0 00-1.023-.55zm5.326 0a7.96 7.96 0 00-1.022.55l2.084 1.063-1.062-2.086zm-2.644.796l-1.063 2.084a7.95 7.95 0 00-2.086-1.062l1.063-2.085a7.963 7.963 0 002.086 1.062zM3.97 13.938a8.015 8.015 0 001.062 2.086l-2.086-1.062zM20.03 13.938a8.015 8.015 0 01-1.062 2.086l2.086-1.062zM15.133 17.777a7.96 7.96 0 001.022-.55l-2.084-1.063 1.062 2.086zm-6.267 0l1.062-2.086-2.084 1.063a7.96 7.96 0 001.022.55zm2.644-.797l1.063-2.084a7.95 7.95 0 002.086 1.062l-1.063 2.085a7.963 7.963 0 01-2.086-1.062zM12 20.03c-3.313 0-6-2.687-6-6 0-.32.006-.641.02-.961l1.062 2.086a7.95 7.95 0 01-2.086-1.062l2.085-1.063A7.963 7.963 0 0112 20.03zm6-6.97a7.963 7.963 0 01-2.086 1.062l1.062-2.086c.014.32.02.641.02.961zm-.796-3.135l-1.062-2.085a7.95 7.95 0 01-2.085 1.062l1.063 2.085a7.963 7.963 0 012.084-1.062zM12 19.969a7.963 7.963 0 001.062-2.086l-1.062 2.086zm-5.325-2.743l-2.086-1.062 1.062-2.085a7.963 7.963 0 002.086 1.062l-1.062 2.085zM9.613 9.365a7.95 7.95 0 002.086-1.062l-1.062 2.086a7.963 7.963 0 00-2.086 1.062l1.062-2.085z" clipRule="evenodd" />
                      </svg>

                      <svg className="w-5 h-5 text-gray-500 transition-transform transform group-hover:rotate-180" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                      </svg>
                    </div>

                    {isEnDropdownOpen && (
                      <ul className="absolute left-0 mt-2 w-48 bg-white text-gray-800 shadow-lg rounded-md group-hover:block transition-opacity duration-300 opacity-100">
                        <li>
                          <Link href="/home/en1" className="block px-4 py-2 hover:bg-gray-100">Deutsch</Link>
                        </li>
                        <li>
                          <Link href="/home/en2" className="block px-4 py-2 hover:bg-gray-100">Español</Link>
                        </li>
                        <li>
                          <Link href="/home/en3" className="block px-4 py-2 hover:bg-gray-100">Français</Link>
                        </li>
                      </ul>
                    )}
                  </li>
                </ul>
              </div>
            )}
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}















